/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AhiruLaunchpad {
  export type TokenStateStruct = {
    tokenAddress: AddressLike;
    name: string;
    symbol: string;
    metadata: string;
    creator: AddressLike;
    soldSupply: BigNumberish;
    totalBNB: BigNumberish;
    initialPrice: BigNumberish;
    totalPlatformFees: BigNumberish;
    totalCreatorFees: BigNumberish;
    bondingCurveLiquidity: BigNumberish;
    liquidityPoolAmount: BigNumberish;
    graduated: boolean;
    exists: boolean;
    createdAt: BigNumberish;
    lastTradeTime: BigNumberish;
  };

  export type TokenStateStructOutput = [
    tokenAddress: string,
    name: string,
    symbol: string,
    metadata: string,
    creator: string,
    soldSupply: bigint,
    totalBNB: bigint,
    initialPrice: bigint,
    totalPlatformFees: bigint,
    totalCreatorFees: bigint,
    bondingCurveLiquidity: bigint,
    liquidityPoolAmount: bigint,
    graduated: boolean,
    exists: boolean,
    createdAt: bigint,
    lastTradeTime: bigint
  ] & {
    tokenAddress: string;
    name: string;
    symbol: string;
    metadata: string;
    creator: string;
    soldSupply: bigint;
    totalBNB: bigint;
    initialPrice: bigint;
    totalPlatformFees: bigint;
    totalCreatorFees: bigint;
    bondingCurveLiquidity: bigint;
    liquidityPoolAmount: bigint;
    graduated: boolean;
    exists: boolean;
    createdAt: bigint;
    lastTradeTime: bigint;
  };
}

export interface AhiruLaunchpadInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "BONDING_CURVE_SPLIT"
      | "CREATE_FEE"
      | "EMERGENCY_TIMELOCK"
      | "E_PRECISION"
      | "FEE_CREATOR_PERCENT"
      | "FEE_PLATFORM_PERCENT"
      | "GRADUATION_TOKEN_ALLOCATION"
      | "GROSS_RAISE_TARGET"
      | "INITIAL_PRICE"
      | "K_FACTOR"
      | "K_PRECISION"
      | "LP_SPLIT"
      | "MAX_EMERGENCY_WITHDRAW"
      | "MAX_EXPONENT"
      | "NET_RAISE_TARGET"
      | "SUPPLY_CONSTANT"
      | "TARGET_SUPPLY"
      | "TIMELOCK_DELAY"
      | "TOTAL_FEE_PERCENT"
      | "TOTAL_SUPPLY"
      | "buy"
      | "completeTreasuryUpdate"
      | "createToken"
      | "deploymentTime"
      | "emergencyMode"
      | "emergencyWithdraw"
      | "getGlobalState"
      | "getSecurityStatus"
      | "getTokenInfo"
      | "globalState"
      | "initiateTreasuryUpdate"
      | "lastEmergencyWithdraw"
      | "owner"
      | "paused"
      | "pendingTreasury"
      | "renounceOwnership"
      | "sell"
      | "setEmergencyMode"
      | "setPause"
      | "transferOwnership"
      | "treasury"
      | "treasuryUpdateTime"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DetailedTransaction"
      | "EmergencyModeChanged"
      | "OwnershipTransferred"
      | "SecurityEvent"
      | "TokenBought"
      | "TokenCreated"
      | "TokenGraduated"
      | "TokenSold"
      | "TreasuryUpdateCompleted"
      | "TreasuryUpdateInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BONDING_CURVE_SPLIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATE_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMERGENCY_TIMELOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "E_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_CREATOR_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_PLATFORM_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GRADUATION_TOKEN_ALLOCATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GROSS_RAISE_TARGET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "K_FACTOR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "K_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "LP_SPLIT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_EMERGENCY_WITHDRAW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EXPONENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NET_RAISE_TARGET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUPPLY_CONSTANT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TARGET_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIMELOCK_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTreasuryUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createToken",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deploymentTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSecurityStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTreasuryUpdate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastEmergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyMode",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "setPause", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "treasuryUpdateTime",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BONDING_CURVE_SPLIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "CREATE_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "EMERGENCY_TIMELOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "E_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_CREATOR_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_PLATFORM_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GRADUATION_TOKEN_ALLOCATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GROSS_RAISE_TARGET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "K_FACTOR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "K_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "LP_SPLIT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EMERGENCY_WITHDRAW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EXPONENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NET_RAISE_TARGET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUPPLY_CONSTANT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TARGET_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIMELOCK_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeTreasuryUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deploymentTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSecurityStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateTreasuryUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasuryUpdateTime",
    data: BytesLike
  ): Result;
}

export namespace DetailedTransactionEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    price: BigNumberish,
    timestamp: BigNumberish,
    gasUsed: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    token: string,
    amount: bigint,
    price: bigint,
    timestamp: bigint,
    gasUsed: bigint
  ];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
    price: bigint;
    timestamp: bigint;
    gasUsed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyModeChangedEvent {
  export type InputTuple = [
    enabled: boolean,
    initiator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    enabled: boolean,
    initiator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    enabled: boolean;
    initiator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecurityEventEvent {
  export type InputTuple = [
    eventType: string,
    user: AddressLike,
    hash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    eventType: string,
    user: string,
    hash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    eventType: string;
    user: string;
    hash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenBoughtEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    buyer: AddressLike,
    bnbAmount: BigNumberish,
    tokenAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    buyer: string,
    bnbAmount: bigint,
    tokenAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    buyer: string;
    bnbAmount: bigint;
    tokenAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenCreatedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    name: string,
    symbol: string,
    creator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    name: string,
    symbol: string,
    creator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    name: string;
    symbol: string;
    creator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenGraduatedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    lpPair: AddressLike,
    lpBNB: BigNumberish,
    lpTokens: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    lpPair: string,
    lpBNB: bigint,
    lpTokens: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    lpPair: string;
    lpBNB: bigint;
    lpTokens: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenSoldEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    seller: AddressLike,
    tokenAmount: BigNumberish,
    bnbAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    seller: string,
    tokenAmount: bigint,
    bnbAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    seller: string;
    tokenAmount: bigint;
    bnbAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdateCompletedEvent {
  export type InputTuple = [
    oldTreasury: AddressLike,
    newTreasury: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldTreasury: string,
    newTreasury: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdateInitiatedEvent {
  export type InputTuple = [newTreasury: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [newTreasury: string, timestamp: bigint];
  export interface OutputObject {
    newTreasury: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AhiruLaunchpad extends BaseContract {
  connect(runner?: ContractRunner | null): AhiruLaunchpad;
  waitForDeployment(): Promise<this>;

  interface: AhiruLaunchpadInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  BONDING_CURVE_SPLIT: TypedContractMethod<[], [bigint], "view">;

  CREATE_FEE: TypedContractMethod<[], [bigint], "view">;

  EMERGENCY_TIMELOCK: TypedContractMethod<[], [bigint], "view">;

  E_PRECISION: TypedContractMethod<[], [bigint], "view">;

  FEE_CREATOR_PERCENT: TypedContractMethod<[], [bigint], "view">;

  FEE_PLATFORM_PERCENT: TypedContractMethod<[], [bigint], "view">;

  GRADUATION_TOKEN_ALLOCATION: TypedContractMethod<[], [bigint], "view">;

  GROSS_RAISE_TARGET: TypedContractMethod<[], [bigint], "view">;

  INITIAL_PRICE: TypedContractMethod<[], [bigint], "view">;

  K_FACTOR: TypedContractMethod<[], [bigint], "view">;

  K_PRECISION: TypedContractMethod<[], [bigint], "view">;

  LP_SPLIT: TypedContractMethod<[], [bigint], "view">;

  MAX_EMERGENCY_WITHDRAW: TypedContractMethod<[], [bigint], "view">;

  MAX_EXPONENT: TypedContractMethod<[], [bigint], "view">;

  NET_RAISE_TARGET: TypedContractMethod<[], [bigint], "view">;

  SUPPLY_CONSTANT: TypedContractMethod<[], [bigint], "view">;

  TARGET_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  TIMELOCK_DELAY: TypedContractMethod<[], [bigint], "view">;

  TOTAL_FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  TOTAL_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  buy: TypedContractMethod<
    [tokenAddress: AddressLike, minTokensOut: BigNumberish],
    [bigint],
    "payable"
  >;

  completeTreasuryUpdate: TypedContractMethod<[], [void], "nonpayable">;

  createToken: TypedContractMethod<
    [name: string, symbol: string, metadata: string],
    [string],
    "payable"
  >;

  deploymentTime: TypedContractMethod<[], [bigint], "view">;

  emergencyMode: TypedContractMethod<[], [boolean], "view">;

  emergencyWithdraw: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getGlobalState: TypedContractMethod<
    [],
    [
      [bigint, bigint, string, boolean, boolean, bigint] & {
        totalTokensCreated: bigint;
        totalFeesCollected: bigint;
        dexRouter: string;
        isPaused: boolean;
        isEmergencyMode: boolean;
        uptime: bigint;
      }
    ],
    "view"
  >;

  getSecurityStatus: TypedContractMethod<
    [],
    [
      [boolean, boolean, bigint, boolean, bigint] & {
        hasValidTreasury: boolean;
        hasPendingTreasuryUpdate: boolean;
        timeSinceLastEmergency: bigint;
        canPerformEmergencyWithdraw: boolean;
        contractAge: bigint;
      }
    ],
    "view"
  >;

  getTokenInfo: TypedContractMethod<
    [tokenAddress: AddressLike],
    [AhiruLaunchpad.TokenStateStructOutput],
    "view"
  >;

  globalState: TypedContractMethod<
    [],
    [
      [bigint, bigint, string] & {
        totalTokensCreated: bigint;
        totalFeesCollected: bigint;
        dexRouter: string;
      }
    ],
    "view"
  >;

  initiateTreasuryUpdate: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  lastEmergencyWithdraw: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingTreasury: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sell: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      tokenAmount: BigNumberish,
      minBNBOut: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  setEmergencyMode: TypedContractMethod<
    [enabled: boolean],
    [void],
    "nonpayable"
  >;

  setPause: TypedContractMethod<[_paused: boolean], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  treasuryUpdateTime: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BONDING_CURVE_SPLIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CREATE_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EMERGENCY_TIMELOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "E_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_CREATOR_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_PLATFORM_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GRADUATION_TOKEN_ALLOCATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GROSS_RAISE_TARGET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "K_FACTOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "K_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LP_SPLIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_EMERGENCY_WITHDRAW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_EXPONENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NET_RAISE_TARGET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SUPPLY_CONSTANT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TARGET_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIMELOCK_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, minTokensOut: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "completeTreasuryUpdate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createToken"
  ): TypedContractMethod<
    [name: string, symbol: string, metadata: string],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deploymentTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getGlobalState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, string, boolean, boolean, bigint] & {
        totalTokensCreated: bigint;
        totalFeesCollected: bigint;
        dexRouter: string;
        isPaused: boolean;
        isEmergencyMode: boolean;
        uptime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSecurityStatus"
  ): TypedContractMethod<
    [],
    [
      [boolean, boolean, bigint, boolean, bigint] & {
        hasValidTreasury: boolean;
        hasPendingTreasuryUpdate: boolean;
        timeSinceLastEmergency: bigint;
        canPerformEmergencyWithdraw: boolean;
        contractAge: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenInfo"
  ): TypedContractMethod<
    [tokenAddress: AddressLike],
    [AhiruLaunchpad.TokenStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, string] & {
        totalTokensCreated: bigint;
        totalFeesCollected: bigint;
        dexRouter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateTreasuryUpdate"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lastEmergencyWithdraw"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      tokenAmount: BigNumberish,
      minBNBOut: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEmergencyMode"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPause"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasuryUpdateTime"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DetailedTransaction"
  ): TypedContractEvent<
    DetailedTransactionEvent.InputTuple,
    DetailedTransactionEvent.OutputTuple,
    DetailedTransactionEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyModeChanged"
  ): TypedContractEvent<
    EmergencyModeChangedEvent.InputTuple,
    EmergencyModeChangedEvent.OutputTuple,
    EmergencyModeChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SecurityEvent"
  ): TypedContractEvent<
    SecurityEventEvent.InputTuple,
    SecurityEventEvent.OutputTuple,
    SecurityEventEvent.OutputObject
  >;
  getEvent(
    key: "TokenBought"
  ): TypedContractEvent<
    TokenBoughtEvent.InputTuple,
    TokenBoughtEvent.OutputTuple,
    TokenBoughtEvent.OutputObject
  >;
  getEvent(
    key: "TokenCreated"
  ): TypedContractEvent<
    TokenCreatedEvent.InputTuple,
    TokenCreatedEvent.OutputTuple,
    TokenCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenGraduated"
  ): TypedContractEvent<
    TokenGraduatedEvent.InputTuple,
    TokenGraduatedEvent.OutputTuple,
    TokenGraduatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenSold"
  ): TypedContractEvent<
    TokenSoldEvent.InputTuple,
    TokenSoldEvent.OutputTuple,
    TokenSoldEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdateCompleted"
  ): TypedContractEvent<
    TreasuryUpdateCompletedEvent.InputTuple,
    TreasuryUpdateCompletedEvent.OutputTuple,
    TreasuryUpdateCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdateInitiated"
  ): TypedContractEvent<
    TreasuryUpdateInitiatedEvent.InputTuple,
    TreasuryUpdateInitiatedEvent.OutputTuple,
    TreasuryUpdateInitiatedEvent.OutputObject
  >;

  filters: {
    "DetailedTransaction(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      DetailedTransactionEvent.InputTuple,
      DetailedTransactionEvent.OutputTuple,
      DetailedTransactionEvent.OutputObject
    >;
    DetailedTransaction: TypedContractEvent<
      DetailedTransactionEvent.InputTuple,
      DetailedTransactionEvent.OutputTuple,
      DetailedTransactionEvent.OutputObject
    >;

    "EmergencyModeChanged(bool,address,uint256)": TypedContractEvent<
      EmergencyModeChangedEvent.InputTuple,
      EmergencyModeChangedEvent.OutputTuple,
      EmergencyModeChangedEvent.OutputObject
    >;
    EmergencyModeChanged: TypedContractEvent<
      EmergencyModeChangedEvent.InputTuple,
      EmergencyModeChangedEvent.OutputTuple,
      EmergencyModeChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SecurityEvent(string,address,bytes32,uint256)": TypedContractEvent<
      SecurityEventEvent.InputTuple,
      SecurityEventEvent.OutputTuple,
      SecurityEventEvent.OutputObject
    >;
    SecurityEvent: TypedContractEvent<
      SecurityEventEvent.InputTuple,
      SecurityEventEvent.OutputTuple,
      SecurityEventEvent.OutputObject
    >;

    "TokenBought(address,address,uint256,uint256,uint256)": TypedContractEvent<
      TokenBoughtEvent.InputTuple,
      TokenBoughtEvent.OutputTuple,
      TokenBoughtEvent.OutputObject
    >;
    TokenBought: TypedContractEvent<
      TokenBoughtEvent.InputTuple,
      TokenBoughtEvent.OutputTuple,
      TokenBoughtEvent.OutputObject
    >;

    "TokenCreated(address,string,string,address,uint256)": TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
    TokenCreated: TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;

    "TokenGraduated(address,address,uint256,uint256,uint256)": TypedContractEvent<
      TokenGraduatedEvent.InputTuple,
      TokenGraduatedEvent.OutputTuple,
      TokenGraduatedEvent.OutputObject
    >;
    TokenGraduated: TypedContractEvent<
      TokenGraduatedEvent.InputTuple,
      TokenGraduatedEvent.OutputTuple,
      TokenGraduatedEvent.OutputObject
    >;

    "TokenSold(address,address,uint256,uint256,uint256)": TypedContractEvent<
      TokenSoldEvent.InputTuple,
      TokenSoldEvent.OutputTuple,
      TokenSoldEvent.OutputObject
    >;
    TokenSold: TypedContractEvent<
      TokenSoldEvent.InputTuple,
      TokenSoldEvent.OutputTuple,
      TokenSoldEvent.OutputObject
    >;

    "TreasuryUpdateCompleted(address,address,uint256)": TypedContractEvent<
      TreasuryUpdateCompletedEvent.InputTuple,
      TreasuryUpdateCompletedEvent.OutputTuple,
      TreasuryUpdateCompletedEvent.OutputObject
    >;
    TreasuryUpdateCompleted: TypedContractEvent<
      TreasuryUpdateCompletedEvent.InputTuple,
      TreasuryUpdateCompletedEvent.OutputTuple,
      TreasuryUpdateCompletedEvent.OutputObject
    >;

    "TreasuryUpdateInitiated(address,uint256)": TypedContractEvent<
      TreasuryUpdateInitiatedEvent.InputTuple,
      TreasuryUpdateInitiatedEvent.OutputTuple,
      TreasuryUpdateInitiatedEvent.OutputObject
    >;
    TreasuryUpdateInitiated: TypedContractEvent<
      TreasuryUpdateInitiatedEvent.InputTuple,
      TreasuryUpdateInitiatedEvent.OutputTuple,
      TreasuryUpdateInitiatedEvent.OutputObject
    >;
  };
}
