/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RabbitLaunchpadInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "BONDING_CURVE_SPLIT"
      | "CREATE_FEE"
      | "DEX_ROUTER_UPDATE_DELAY"
      | "EMERGENCY_COOLDOWN"
      | "E_PRECISION"
      | "FEE_CREATOR_PERCENT"
      | "FEE_PLATFORM_PERCENT"
      | "GRADUATION_TOKEN_ALLOCATION"
      | "GROSS_RAISE_TARGET"
      | "INITIAL_PRICE"
      | "K_FACTOR"
      | "K_PRECISION"
      | "LP_SPLIT"
      | "MAX_EXPONENT"
      | "MAX_PURCHASE_AMOUNT"
      | "MAX_SINGLE_SELL"
      | "MIN_PURCHASE_AMOUNT"
      | "NET_RAISE_TARGET"
      | "SUPPLY_CONSTANT"
      | "TARGET_SUPPLY"
      | "TOTAL_FEE_PERCENT"
      | "TOTAL_SUPPLY"
      | "TREASURY_UPDATE_DELAY"
      | "activateEmergencyMode"
      | "buy"
      | "calculatePrice"
      | "calculateTokenPurchase"
      | "calculateTokenSale"
      | "completeDexRouterUpdate"
      | "completeTreasuryUpdate"
      | "contractBalance"
      | "createToken"
      | "deactivateEmergencyMode"
      | "dexRouter"
      | "dexRouterUpdateTime"
      | "emergencyMode"
      | "emergencyTokenRecovery"
      | "emergencyWithdraw"
      | "getAllTokens"
      | "getBondingCurveStats"
      | "getTokenInfo"
      | "graduate"
      | "initiateDexRouterUpdate"
      | "initiateTreasuryUpdate"
      | "isEmergencyMode"
      | "isPaused"
      | "lastEmergencyAction"
      | "owner"
      | "pause"
      | "paused"
      | "pendingDexRouter"
      | "pendingTreasury"
      | "renounceOwnership"
      | "sell"
      | "totalFeesCollected"
      | "transferOwnership"
      | "treasury"
      | "treasuryUpdateTime"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractStateChanged"
      | "EmergencyAction"
      | "ExternalCallResult"
      | "OwnershipTransferred"
      | "SecurityEvent"
      | "TokenCreated"
      | "TokenGraduated"
      | "TokensPurchased"
      | "TokensSold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BONDING_CURVE_SPLIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATE_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEX_ROUTER_UPDATE_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMERGENCY_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "E_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_CREATOR_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_PLATFORM_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GRADUATION_TOKEN_ALLOCATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GROSS_RAISE_TARGET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "K_FACTOR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "K_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "LP_SPLIT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_EXPONENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PURCHASE_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SINGLE_SELL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_PURCHASE_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NET_RAISE_TARGET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUPPLY_CONSTANT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TARGET_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_UPDATE_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activateEmergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "buy", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "calculatePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTokenPurchase",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTokenSale",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeDexRouterUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeTreasuryUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createToken",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateEmergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dexRouter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "dexRouterUpdateTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyTokenRecovery",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBondingCurveStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "graduate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateDexRouterUpdate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTreasuryUpdate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEmergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastEmergencyAction",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingDexRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "treasuryUpdateTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BONDING_CURVE_SPLIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "CREATE_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEX_ROUTER_UPDATE_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMERGENCY_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "E_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_CREATOR_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_PLATFORM_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GRADUATION_TOKEN_ALLOCATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GROSS_RAISE_TARGET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "K_FACTOR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "K_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "LP_SPLIT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EXPONENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PURCHASE_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SINGLE_SELL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_PURCHASE_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NET_RAISE_TARGET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUPPLY_CONSTANT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TARGET_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_UPDATE_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateEmergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTokenPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTokenSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeDexRouterUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeTreasuryUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateEmergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dexRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dexRouterUpdateTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyTokenRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBondingCurveStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "graduate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateDexRouterUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateTreasuryUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEmergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastEmergencyAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingDexRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasuryUpdateTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace ContractStateChangedEvent {
  export type InputTuple = [
    paused: boolean,
    emergencyMode: boolean,
    timestamp: BigNumberish,
    changer: AddressLike
  ];
  export type OutputTuple = [
    paused: boolean,
    emergencyMode: boolean,
    timestamp: bigint,
    changer: string
  ];
  export interface OutputObject {
    paused: boolean;
    emergencyMode: boolean;
    timestamp: bigint;
    changer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyActionEvent {
  export type InputTuple = [
    caller: AddressLike,
    action: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [caller: string, action: string, timestamp: bigint];
  export interface OutputObject {
    caller: string;
    action: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExternalCallResultEvent {
  export type InputTuple = [
    target: AddressLike,
    amount: BigNumberish,
    success: boolean
  ];
  export type OutputTuple = [target: string, amount: bigint, success: boolean];
  export interface OutputObject {
    target: string;
    amount: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecurityEventEvent {
  export type InputTuple = [
    eventType: string,
    user: AddressLike,
    value: BigNumberish,
    timestamp: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    eventType: string,
    user: string,
    value: bigint,
    timestamp: bigint,
    reason: string
  ];
  export interface OutputObject {
    eventType: string;
    user: string;
    value: bigint;
    timestamp: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    tokenAddress: AddressLike,
    name: string,
    symbol: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    tokenAddress: string,
    name: string,
    symbol: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    creator: string;
    tokenAddress: string;
    name: string;
    symbol: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenGraduatedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    creator: AddressLike,
    totalRaised: BigNumberish,
    totalSold: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    creator: string,
    totalRaised: bigint,
    totalSold: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    creator: string;
    totalRaised: bigint;
    totalSold: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    tokenAddress: AddressLike,
    bnbAmount: BigNumberish,
    tokenAmount: BigNumberish,
    price: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    tokenAddress: string,
    bnbAmount: bigint,
    tokenAmount: bigint,
    price: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    buyer: string;
    tokenAddress: string;
    bnbAmount: bigint;
    tokenAmount: bigint;
    price: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensSoldEvent {
  export type InputTuple = [
    seller: AddressLike,
    tokenAddress: AddressLike,
    tokenAmount: BigNumberish,
    bnbAmount: BigNumberish,
    price: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    tokenAddress: string,
    tokenAmount: bigint,
    bnbAmount: bigint,
    price: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    seller: string;
    tokenAddress: string;
    tokenAmount: bigint;
    bnbAmount: bigint;
    price: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RabbitLaunchpad extends BaseContract {
  connect(runner?: ContractRunner | null): RabbitLaunchpad;
  waitForDeployment(): Promise<this>;

  interface: RabbitLaunchpadInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  BONDING_CURVE_SPLIT: TypedContractMethod<[], [bigint], "view">;

  CREATE_FEE: TypedContractMethod<[], [bigint], "view">;

  DEX_ROUTER_UPDATE_DELAY: TypedContractMethod<[], [bigint], "view">;

  EMERGENCY_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  E_PRECISION: TypedContractMethod<[], [bigint], "view">;

  FEE_CREATOR_PERCENT: TypedContractMethod<[], [bigint], "view">;

  FEE_PLATFORM_PERCENT: TypedContractMethod<[], [bigint], "view">;

  GRADUATION_TOKEN_ALLOCATION: TypedContractMethod<[], [bigint], "view">;

  GROSS_RAISE_TARGET: TypedContractMethod<[], [bigint], "view">;

  INITIAL_PRICE: TypedContractMethod<[], [bigint], "view">;

  K_FACTOR: TypedContractMethod<[], [bigint], "view">;

  K_PRECISION: TypedContractMethod<[], [bigint], "view">;

  LP_SPLIT: TypedContractMethod<[], [bigint], "view">;

  MAX_EXPONENT: TypedContractMethod<[], [bigint], "view">;

  MAX_PURCHASE_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  MAX_SINGLE_SELL: TypedContractMethod<[], [bigint], "view">;

  MIN_PURCHASE_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  NET_RAISE_TARGET: TypedContractMethod<[], [bigint], "view">;

  SUPPLY_CONSTANT: TypedContractMethod<[], [bigint], "view">;

  TARGET_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  TOTAL_FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  TOTAL_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  TREASURY_UPDATE_DELAY: TypedContractMethod<[], [bigint], "view">;

  activateEmergencyMode: TypedContractMethod<[], [void], "nonpayable">;

  buy: TypedContractMethod<[tokenAddress: AddressLike], [void], "payable">;

  calculatePrice: TypedContractMethod<[supply: BigNumberish], [bigint], "view">;

  calculateTokenPurchase: TypedContractMethod<
    [
      currentSupply: BigNumberish,
      bnbAmount: BigNumberish,
      initialPrice: BigNumberish,
      slope: BigNumberish
    ],
    [bigint],
    "view"
  >;

  calculateTokenSale: TypedContractMethod<
    [
      currentSupply: BigNumberish,
      tokenAmount: BigNumberish,
      initialPrice: BigNumberish,
      slope: BigNumberish
    ],
    [bigint],
    "view"
  >;

  completeDexRouterUpdate: TypedContractMethod<[], [void], "nonpayable">;

  completeTreasuryUpdate: TypedContractMethod<[], [void], "nonpayable">;

  contractBalance: TypedContractMethod<[], [bigint], "view">;

  createToken: TypedContractMethod<
    [name: string, symbol: string],
    [void],
    "payable"
  >;

  deactivateEmergencyMode: TypedContractMethod<[], [void], "nonpayable">;

  dexRouter: TypedContractMethod<[], [string], "view">;

  dexRouterUpdateTime: TypedContractMethod<[], [bigint], "view">;

  emergencyMode: TypedContractMethod<[], [boolean], "view">;

  emergencyTokenRecovery: TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllTokens: TypedContractMethod<[], [string[]], "view">;

  getBondingCurveStats: TypedContractMethod<
    [tokenAddress: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        currentPrice: bigint;
        nextBuyPrice: bigint;
        nextSellPrice: bigint;
        supplyProgress: bigint;
        raiseProgress: bigint;
        canGraduate: boolean;
      }
    ],
    "view"
  >;

  getTokenInfo: TypedContractMethod<
    [tokenAddress: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean, boolean, bigint, bigint] & {
        creator: string;
        totalRaised: bigint;
        soldSupply: bigint;
        creationTime: bigint;
        exists: boolean;
        graduated: boolean;
        graduationPrice: bigint;
        currentPrice: bigint;
      }
    ],
    "view"
  >;

  graduate: TypedContractMethod<
    [tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  initiateDexRouterUpdate: TypedContractMethod<
    [newDexRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  initiateTreasuryUpdate: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  isEmergencyMode: TypedContractMethod<[], [boolean], "view">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  lastEmergencyAction: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingDexRouter: TypedContractMethod<[], [string], "view">;

  pendingTreasury: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sell: TypedContractMethod<
    [tokenAddress: AddressLike, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  treasuryUpdateTime: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BONDING_CURVE_SPLIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CREATE_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEX_ROUTER_UPDATE_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EMERGENCY_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "E_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_CREATOR_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_PLATFORM_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GRADUATION_TOKEN_ALLOCATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GROSS_RAISE_TARGET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "K_FACTOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "K_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LP_SPLIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_EXPONENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PURCHASE_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SINGLE_SELL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PURCHASE_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NET_RAISE_TARGET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SUPPLY_CONSTANT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TARGET_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREASURY_UPDATE_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activateEmergencyMode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<[tokenAddress: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "calculatePrice"
  ): TypedContractMethod<[supply: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateTokenPurchase"
  ): TypedContractMethod<
    [
      currentSupply: BigNumberish,
      bnbAmount: BigNumberish,
      initialPrice: BigNumberish,
      slope: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateTokenSale"
  ): TypedContractMethod<
    [
      currentSupply: BigNumberish,
      tokenAmount: BigNumberish,
      initialPrice: BigNumberish,
      slope: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "completeDexRouterUpdate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeTreasuryUpdate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createToken"
  ): TypedContractMethod<[name: string, symbol: string], [void], "payable">;
  getFunction(
    nameOrSignature: "deactivateEmergencyMode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dexRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dexRouterUpdateTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyTokenRecovery"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBondingCurveStats"
  ): TypedContractMethod<
    [tokenAddress: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        currentPrice: bigint;
        nextBuyPrice: bigint;
        nextSellPrice: bigint;
        supplyProgress: bigint;
        raiseProgress: bigint;
        canGraduate: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenInfo"
  ): TypedContractMethod<
    [tokenAddress: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean, boolean, bigint, bigint] & {
        creator: string;
        totalRaised: bigint;
        soldSupply: bigint;
        creationTime: bigint;
        exists: boolean;
        graduated: boolean;
        graduationPrice: bigint;
        currentPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "graduate"
  ): TypedContractMethod<[tokenAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initiateDexRouterUpdate"
  ): TypedContractMethod<[newDexRouter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initiateTreasuryUpdate"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isEmergencyMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastEmergencyAction"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingDexRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasuryUpdateTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ContractStateChanged"
  ): TypedContractEvent<
    ContractStateChangedEvent.InputTuple,
    ContractStateChangedEvent.OutputTuple,
    ContractStateChangedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyAction"
  ): TypedContractEvent<
    EmergencyActionEvent.InputTuple,
    EmergencyActionEvent.OutputTuple,
    EmergencyActionEvent.OutputObject
  >;
  getEvent(
    key: "ExternalCallResult"
  ): TypedContractEvent<
    ExternalCallResultEvent.InputTuple,
    ExternalCallResultEvent.OutputTuple,
    ExternalCallResultEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SecurityEvent"
  ): TypedContractEvent<
    SecurityEventEvent.InputTuple,
    SecurityEventEvent.OutputTuple,
    SecurityEventEvent.OutputObject
  >;
  getEvent(
    key: "TokenCreated"
  ): TypedContractEvent<
    TokenCreatedEvent.InputTuple,
    TokenCreatedEvent.OutputTuple,
    TokenCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenGraduated"
  ): TypedContractEvent<
    TokenGraduatedEvent.InputTuple,
    TokenGraduatedEvent.OutputTuple,
    TokenGraduatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensPurchased"
  ): TypedContractEvent<
    TokensPurchasedEvent.InputTuple,
    TokensPurchasedEvent.OutputTuple,
    TokensPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "TokensSold"
  ): TypedContractEvent<
    TokensSoldEvent.InputTuple,
    TokensSoldEvent.OutputTuple,
    TokensSoldEvent.OutputObject
  >;

  filters: {
    "ContractStateChanged(bool,bool,uint256,address)": TypedContractEvent<
      ContractStateChangedEvent.InputTuple,
      ContractStateChangedEvent.OutputTuple,
      ContractStateChangedEvent.OutputObject
    >;
    ContractStateChanged: TypedContractEvent<
      ContractStateChangedEvent.InputTuple,
      ContractStateChangedEvent.OutputTuple,
      ContractStateChangedEvent.OutputObject
    >;

    "EmergencyAction(address,string,uint256)": TypedContractEvent<
      EmergencyActionEvent.InputTuple,
      EmergencyActionEvent.OutputTuple,
      EmergencyActionEvent.OutputObject
    >;
    EmergencyAction: TypedContractEvent<
      EmergencyActionEvent.InputTuple,
      EmergencyActionEvent.OutputTuple,
      EmergencyActionEvent.OutputObject
    >;

    "ExternalCallResult(address,uint256,bool)": TypedContractEvent<
      ExternalCallResultEvent.InputTuple,
      ExternalCallResultEvent.OutputTuple,
      ExternalCallResultEvent.OutputObject
    >;
    ExternalCallResult: TypedContractEvent<
      ExternalCallResultEvent.InputTuple,
      ExternalCallResultEvent.OutputTuple,
      ExternalCallResultEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SecurityEvent(string,address,uint256,uint256,string)": TypedContractEvent<
      SecurityEventEvent.InputTuple,
      SecurityEventEvent.OutputTuple,
      SecurityEventEvent.OutputObject
    >;
    SecurityEvent: TypedContractEvent<
      SecurityEventEvent.InputTuple,
      SecurityEventEvent.OutputTuple,
      SecurityEventEvent.OutputObject
    >;

    "TokenCreated(address,address,string,string,uint256)": TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;
    TokenCreated: TypedContractEvent<
      TokenCreatedEvent.InputTuple,
      TokenCreatedEvent.OutputTuple,
      TokenCreatedEvent.OutputObject
    >;

    "TokenGraduated(address,address,uint256,uint256,uint256)": TypedContractEvent<
      TokenGraduatedEvent.InputTuple,
      TokenGraduatedEvent.OutputTuple,
      TokenGraduatedEvent.OutputObject
    >;
    TokenGraduated: TypedContractEvent<
      TokenGraduatedEvent.InputTuple,
      TokenGraduatedEvent.OutputTuple,
      TokenGraduatedEvent.OutputObject
    >;

    "TokensPurchased(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
    TokensPurchased: TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;

    "TokensSold(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TokensSoldEvent.InputTuple,
      TokensSoldEvent.OutputTuple,
      TokensSoldEvent.OutputObject
    >;
    TokensSold: TypedContractEvent<
      TokensSoldEvent.InputTuple,
      TokensSoldEvent.OutputTuple,
      TokensSoldEvent.OutputObject
    >;
  };
}
